<!-- header -->
<header class="g-header">
	header
</header>
<!-- <nav class="g-nav fl">
	<nav class="g-nav">
		<ul>
			<li>
				<a href="./index.html" @if (context.active==='index') { class="active" }>首页</a>
			</li>
			<li>
				<a href="./qidoubao.html" @if (context.active==='service') { class="active" }>产品服务</a>
			</li>
			<li>
				<a href="./case.html" @if (context.active==='case') { class="active" }>成功案例</a>
			</li>
			<li class="about">
				<a href="javascript:;" @if (context.active==='about') { class="active" }>关于我们<span class="arrow"></span></a>
					<div class="subnav list-nav">
						<p><a href="./about.html">公司介绍</a></p>
						<p><a href="./newslist.html">新闻资讯</a></p>
					</div>
			</li>
			<li>
				<a href="./contact.html" @if (context.active==='contact') { class="active" }>联系我们</a>
			</li>
		</ul>
	</nav>
</nav> -->